source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# gem "trailblazer-operation"
# # gem "trailblazer-context", path: "../../../trailblazer-context"
# gem "trailblazer-activity-dsl-linear", path: "../../../trailblazer-activity-dsl-linear"
# gem "trailblazer-activity", path: "../../../trailblazer-activity"


gem "trailblazer-endpoint", path: "../../."
gem "jwt"
gem "multi_json"
gem "minitest-line"
gem "trailblazer-cells"
gem "cells-erb"
gem "cells-rails"
gem "representable"
gem "trailblazer-operation"

# FIXME
# gem "trailblazer-workflow", path: "../../../trailblazer-workflow"
# gem "trailblazer-activity",             path: "../../../trailblazer-activity"
# gem "trailblazer-activity-dsl-linear",  path: "../../../trailblazer-activity-dsl-linear"
# gem "trailblazer-operation",            path: "../../../trailblazer-operation"
# gem "trailblazer-developer",            path: "../../../trailblazer-developer"
