source "https://rubygems.org"

gem "multi_json"
# Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "rails", "~> 5.0.0", ">= 5.0.0.1"
# Use sqlite3 as the database for Active Record
gem "sqlite3"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

gem "trailblazer"
gem "trailblazer-endpoint", path: "../../."
gem "trailblazer-operation"
